#!/bin/bash
#
# Lazyscripts launcher wrapper
#
# @author '2009 Hsin Yi Chen (陳信屹) <ossug.hychen@gmail.com>'

# update lazyscripts.
set -o xtrace

source startup.sh

# run Lazyscripts with root access
case $DISTRO_ID in
    "Ubuntu")

    gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" --preserve-env tmp/env-export.sh $@
    ;;
    "Debian")

    gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" tmp/env-export.sh $@
    ;;
    "openSUSE")
    case $WIN_MGR in
#FIXME: arguments?
        'Gnome')
        gnomesu --command="tmp/env-export.sh $@"
        ;;
        'KDE')
        PWD=$(pwd)
        kdesu -c "cd $PWD ; tmp/env-export.sh $@"
        ;;
        *)
        PWD=$(pwd)
        xdg-su -c "cd $PWD ; tmp/env-export.sh $@"
        ;;
    esac
    ;;
    "Fedora"|"CentOS")
    if rpm -q gksu &> /dev/null ; then
        gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" --preserve-env tmp/env-export.sh $@
    else
        zenity --info --text "Sorry, you need to install gksu before run Lazyscripts. Please install gksu first.\n\ncomment: you can install through run distrib/${DISTRO_ID}/run_first.sh"
    fi
    ;;
    "Mandriva")
    if rpm -q gksu &> /dev/null ; then
        gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" tmp/env-export.sh $@
    else
        zenity --info --text "Sorry, you need to install gksu before run Lazyscripts. Please install gksu first.\n\ncomment: you can install through run distrib/${DISTRO_ID}/run_first.sh"
    fi
    ;;
    "OpenSolaris")
    gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" tmp/env-export.sh $@
    ;;
    *)
    echo "Lazyscripts not support $DISTRO_ID ."
    ;;
esac
