#!/bin/bash
#
# Lazyscripts launcher wrapper
#
# @author '2009 Hsin Yi Chen (陳信屹) <ossug.hychen@gmail.com>'

# update lazyscripts.
set -o xtrace

# some workaround
DIR=`dirname $0`
cd "$DIR"
DIR=$(pwd)

USER_ID=$(id -u)
if [ $USER_ID == 0 ]; then
    echo "Don't run this file as root."
    exit
fi

source startup.sh

# run Lazyscripts with root access

if [ ! $@ == "test-env" ];then
case $DISTRO_ID in
    "Ubuntu")
    case $WIN_MGR in
        'Gnome'|'LXDE'|'Xfce')
        gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" --preserve-env tmp/env-export.sh $@
        ;;
        'KDE')
        if which kdesudo &> /dev/null ; then
            kdesudo -c "tmp/env-export.sh $@"
        else
            kdesu -c "tmp/env-export.sh $@"
        fi
        ;;
        *)
# Try to use gksu
        gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" --preserve-env tmp/env-export.sh $@
        ;;
    esac

    ;;
    "Debian")
    case $WIN_MGR in
        'Gnome'|'LXDE'|'Xfce')
        gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" tmp/env-export.sh $@
        ;;
        'KDE')
        if dpkg -l kdesudo &> /dev/null ; then
            if which kdesudo &> /dev/null ; then
                kdesudo -c "tmp/env-export.sh $@"
            else
                kdesu -c "tmp/env-export.sh $@"
            fi
        else
            gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" tmp/env-export.sh $@
        fi
        ;;
        *)
# Try to use gksu
        gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" tmp/env-export.sh $@
        ;;
    esac
    ;;
    "openSUSE")
    case $WIN_MGR in
#FIXME: arguments?
        'Gnome')
        gnomesu --command="tmp/env-export.sh $@"
        ;;
        'KDE')
        PWD_DIR=$(pwd)
        kdesu -c "cd $PWD_DIR ; tmp/env-export.sh $@"
        ;;
        *)
        PWD_DIR=$(pwd)
        xdg-su -c "tmp/env-export.sh $@"
        ;;
    esac
    ;;
    "Fedora"|"CentOS")
    if rpm -q gksu &> /dev/null ; then
        gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" --preserve-env tmp/env-export.sh $@
    else
        zenity --info --text "Sorry, you need to install gksu before run Lazyscripts. Please install gksu first.\n\ncomment: you can install through run distrib/${DISTRO_ID}/run_first.sh"
    fi
    ;;
    "Mandriva")
    if rpm -q gksu &> /dev/null ; then
        gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" tmp/env-export.sh $@
    else
        zenity --info --text "Sorry, you need to install gksu before run Lazyscripts. Please install gksu first.\n\ncomment: you can install through run distrib/${DISTRO_ID}/run_first.sh"
    fi
    ;;
    "Arch")
    if pacman -Qs gksu; then
        gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" --preserve-env tmp/env-export.sh $@
    elif pacman -Qs kdesu ; then
        kdesu -c "tmp/env-export.sh $@"
# Try to use gksu
    else 
        su -c "tmp/env-export.sh $@"
    fi

    ;;
    "OpenSolaris")
    gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" tmp/env-export.sh $@
    ;;
    "LinuxMint")
    case $WIN_MGR in
        'Gnome'|'LXDE'|'Xfce')
        gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" --preserve-env tmp/env-export.sh $@
        ;;
        'KDE')
        if which kdesudo &> /dev/null ; then
            kdesudo -c "tmp/env-export.sh $@"
        else
            kdesu -c "tmp/env-export.sh $@"
        fi
        ;;
        *)
# Try to use gksu
        gksu --message "執行 'Lazyscripts 懶人包' 會修改系統設定，並會安裝新軟體，所以需要系統管理員權限。 請輸入系統管理密碼，才能繼續執行。 (在 Lazyscripts 下，預設這就是你登入系統時所用的密碼。)" --preserve-env tmp/env-export.sh $@
        ;;
    esac

    ;;
    *)
    echo "Lazyscripts not support $DISTRO_ID ."
    ;;
esac
else
    su -c "tmp/env-export.sh"
fi
