
##Python 
PYTHON_VERSION = '2.6.0'

### DISTRIBUTION
# Debian base
DISTRIBUTION_DEBIAN = 'debian'
DISTRIBUTION_UBUNTU = 'ubuntu'
DISTRIBUTION_LINUXMINT = 'linuxmint'

DISTRIBUTION_DEB_BASE = \
        (DISTRIBUTION_DEBIAN,
         DISTRIBUTION_UBUNTU,
         DISTRIBUTION_LINUXMINT)


# RPM Base
DISTRIBUTION_REDHAT = 'redhat'
DISTRIBUTION_CENTOS = 'centos'
DISTRIBUTION_FEDORA = 'fedora'

DISTRIBUTION_SUSE = 'suse'
DISTRIBUTION_OPENSUSE = 'opensuse'
DISTRIBUTION_MANDRIVA = 'mandriva'

DISTRIBUTION_RPM_BASE = \
        (DISTRIBUTION_REDHAT,
         DISTRIBUTION_CENTOS,
         DISTRIBUTION_FEDORA,
         DISTRIBUTION_SUSE,
         DISTRIBUTION_OPENSUSE,
         DISTRIBUTION_MANDRIVA)

### Architecture
ARCHITECTURE_I386 = 'i386'
ARCHITECTURE_AMD64 = 'amd64'
